name: shopper
description: A Flutter E-Commerce App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  flare_flutter: ^2.0.6
  flutter_spinkit: "^4.1.2"
  flutter_svg: ^0.19.0
  firebase_storage: ^4.0.0
  image_picker: ^0.6.7+7
  hexcolor: ^1.0.4
  flutter_slidable:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/product_sans_bold.ttf
        - asset: fonts/product_sans_regular.ttf
          style: normal
